Citizen.CreateThread(function()
    AddTextEntry('FE_THDR_GTAO', '~b~Bienvenido a SERVER NAME - discord.gg/servername')
    AddTextEntry('PM_PANE_LEAVE', '~r~Desconectarse')
    AddTextEntry('PM_PANE_QUIT', '~r~Cerrar FiveM')
    AddTextEntry('PM_SCR_MAP', '~p~Mapa de SERVER NAME')
    AddTextEntry('PM_SCR_GAM', '~p~Salir')
    AddTextEntry('PM_SCR_INF', '~p~Logs')
    AddTextEntry('PM_SCR_SET', '~p~Configuración')
    AddTextEntry('PM_SCR_STA', '~p~Estadística')
    AddTextEntry('PM_SCR_RPL', '~p~Editor')
  end)